version: '3'

services:
  db:
    container_name: db
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordsec
      MYSQL_DATABASE: MyWordPressTest
      MYSQL_USER: MyWordPressTest
      MYSQL_PASSWORD: wordsec
    expose:
      - 3306
      - 33060
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network
  wordpress:
    depends_on:
      - db
    image: wordpress
    ports:
      - 80:80
    volumes:
      - ./wp-connect:/var/www/html/wp-connect
      - db_data:/var/lib/mysql
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: MyWordPressTest
      WORDPRESS_DB_PASSWORD: wordsec
      WORDPRESS_DB_NAME: MyWordPressTest
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
   driver: bridge